"""Goal Entity Models for OntologyAI V6.

Defines the domain models for the Goal Runtime — the persistent business
object that agents continuously work toward. Every agent in the system
advances one or more Goals by producing Observations, Plans, Decisions,
and Reviews.

Architecture (from the pivot narrative):

    Enterprise Events
            ↓
    Evidence Runtime
            ↓
    Knowledge Runtime
            ↓
    Memory Runtime
            ↓
    **Goal Runtime**  ← This module
            ↓
    Decision Runtime
            ↓
    Workspace Runtime

FROZEN — V6.0 M0.5
"""

from __future__ import annotations

from datetime import datetime, timezone
from enum import Enum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field

from src.entities.models import OntologyBaseModel


# ── Enums ────────────────────────────────────────────────────────────────


class GoalStatus(str, Enum):
    """Lifecycle status of a Goal."""

    PENDING = "pending"  # Created but not yet active
    ACTIVE = "active"  # Agent is actively working on this goal
    STALLED = "stalled"  # Agent is blocked, needs human intervention
    COMPLETED = "completed"  # Goal has been achieved (KPIs met)
    FAILED = "failed"  # Goal could not be achieved
    ARCHIVED = "archived"  # Retired / no longer relevant


class ObservationType(str, Enum):
    """Type of evidence observed for a goal."""

    KPI = "kpi"  # Quantitative metric change
    EVENT = "event"  # Qualitative event (incident, meeting, etc.)
    SIGNAL = "signal"  # Early warning / leading indicator
    DECISION = "decision"  # Decision made about this goal


# ── Core Entities ──────────────────────────────────────────────────────────


class GoalKPI(OntologyBaseModel):
    """Key Performance Indicator tied to a Goal.

    Parameters
    ----------
    id : str
        Unique identifier for this KPI (e.g. ULID).
    goal_id : str
        The Goal this KPI belongs to.
    name : str
        Human-readable name (e.g. "Monthly Churn Rate").
    target_value : float
        The desired value.
    baseline_value : float
        Where we started.
    current_value : float | None
        Latest observed value (None = not yet measured).
    unit : str
        Units (e.g. "percentage", "dollars", "count").
    direction : Literal["increase", "decrease", "stable"]
        Whether the goal wants the KPI to increase or decrease.
    """

    id: str
    goal_id: str
    name: str
    target_value: float
    baseline_value: float
    current_value: float | None = None
    unit: str
    direction: str = "decrease"


class GoalObservation(OntologyBaseModel):
    """An observation of evidence related to a Goal.

    Observations are produced continuously by the Discovery Agent or
    pushed by the Evidence Runtime when new evidence matches a goal's
    domain.

    Parameters
    ----------
    id : str
        Unique observation ID.
    goal_id : str
        The Goal this observation relates to.
    type : ObservationType
        What kind of observation this is.
    source : str
        Source system (e.g. "slack", "salesforce", "jira").
    content : str
        Human-readable summary of the observation.
    evidence_ids : list[str]
        IDs of EvidenceRecords this observation is derived from.
    confidence : float
        Confidence in the observation (0.0–1.0).
    timestamp : datetime
        When the observation was made.
    """

    id: str
    goal_id: str
    type: ObservationType
    source: str
    content: str
    evidence_ids: list[str] = Field(default_factory=list)
    confidence: float = Field(ge=0.0, le=1.0)
    timestamp: datetime


class GoalPlan(OntologyBaseModel):
    """A plan for advancing a Goal.

    Plans are generated by the Decision Runtime when a Goal needs action.

    Parameters
    ----------
    id : str
        Unique plan ID.
    goal_id : str
        The Goal this plan advances.
    decision_id : str | None
        The Decision that produced this plan (if any).
    title : str
        Short title of the plan.
    description : str
        What the plan does.
    steps : list[str]
        Ordered list of actions.
    confidence : float
        Confidence the plan will achieve the goal (0.0–1.0).
    created_at : datetime
    status : Literal["proposed", "executing", "completed", "failed"]
    """

    id: str
    goal_id: str
    decision_id: str | None = None
    title: str
    description: str = ""
    steps: list[str] = Field(default_factory=list)
    confidence: float = Field(ge=0.0, le=1.0)
    created_at: datetime
    status: str = "proposed"


class GoalReview(OntologyBaseModel):
    """A periodic review of a Goal's progress.

    Parameters
    ----------
    id : str
        Unique review ID.
    goal_id : str
        The Goal reviewed.
    timestamp : datetime
        When the review was conducted.
    kpi_scores : dict[str, float]
        Mapping of KPI name → current value at review time.
    goal_confidence : float
        Updated overall confidence in achieving the goal (0.0–1.0).
    recommendation : str
        Text recommendation from the review.
    triggered_replan : bool
        Whether the review triggered a replan.
    """

    id: str
    goal_id: str
    timestamp: datetime
    kpi_scores: dict[str, float] = Field(default_factory=dict)
    goal_confidence: float = Field(ge=0.0, le=1.0)
    recommendation: str = ""
    triggered_replan: bool = False


class Goal(OntologyBaseModel):
    """A persistent business goal that agents continuously advance.

    A Goal is the central business object connecting enterprise events to
    decisions and workspaces. Goals run as long-running Temporal workflows
    that wake on events, evaluate new evidence, and replan as needed.

    Parameters
    ----------
    id : str
        Unique Goal identifier (ULID-style).
    tenant_id : str
        Multi-tenant isolation.
    title : str
        Human-readable goal (e.g. "Reduce Enterprise Churn").
    description : str
        Longer description of what the goal aims to achieve.
    owner_id : str
        Human or system owner of the goal.
    status : GoalStatus
        Current lifecycle status.
    kpis : list[GoalKPI]
        KPIs tracked for this goal.
    observations : list[GoalObservation]
        Chronological observations.
    plans : list[GoalPlan]
        Plans generated for this goal.
    reviews : list[GoalReview]
        Periodic reviews.
    next_review_at : datetime | None
        When the next scheduled review should occur.
    confidence : float
        Overall confidence in achieving the goal (0.0–1.0).
    created_at : datetime
    updated_at : datetime
    metadata : dict[str, Any]
        Arbitrary key-value metadata for extensibility.
    """

    id: str
    tenant_id: str
    title: str
    description: str = ""
    owner_id: str
    status: GoalStatus = GoalStatus.PENDING
    kpis: list[GoalKPI] = Field(default_factory=list)
    observations: list[GoalObservation] = Field(default_factory=list)
    plans: list[GoalPlan] = Field(default_factory=list)
    reviews: list[GoalReview] = Field(default_factory=list)
    next_review_at: datetime | None = None
    confidence: float = Field(default=0.0, ge=0.0, le=1.0)
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    updated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    metadata: dict[str, Any] = Field(default_factory=dict)


# ── Value Objects ──────────────────────────────────────────────────────────


class GoalProgress:
    """Aggregated progress snapshot for a Goal.

    Parameters
    ----------
    goal_id : str
    kpi_scores : dict[str, float]
        Current value for each tracked KPI.
    confidence : float
        Updated confidence after this progress tick.
    status : GoalStatus
    next_review_at : datetime | None
    """

    __slots__ = (
        "goal_id",
        "kpi_scores",
        "confidence",
        "status",
        "next_review_at",
    )

    def __init__(
        self,
        goal_id: str,
        kpi_scores: dict[str, float],
        confidence: float,
        status: GoalStatus,
        next_review_at: datetime | None = None,
    ) -> None:
        self.goal_id = goal_id
        self.kpi_scores = kpi_scores
        self.confidence = confidence
        self.status = status
        self.next_review_at = next_review_at

    def __repr__(self) -> str:
        return (
            f"GoalProgress(goal={self.goal_id!r}, "
            f"status={self.status.value!r}, confidence={self.confidence:.2f})"
        )


__all__ = [
    "Goal",
    "GoalKPI",
    "GoalObservation",
    "GoalPlan",
    "GoalReview",
    "GoalStatus",
    "ObservationType",
    "GoalProgress",
]
